### ISSUE TITLE
Issue with overlapping IDs in inventory

### ISSUE THREAD

**Issue by JesseBoogaard** [Lenkaaad/DoGotchiBot#5]
![afbeelding](https://user-images.githubusercontent.com/16187312/44355631-696f4f00-a4ad-11e8-8f52-309ba1edfac1.png)

2 different items with different values were categorized under slot "1" in dogotchi's inventory

when selling them both items were assigned the value of the item that was in slot 1 the first, making me lose a significant amount of money and the item in question as seen in the image attached

**Comment by Lenkaaad** [comment]
Fixed with latest commit
